// <auto-generated />
using System;
using CloneBE.Infraction.Presistences;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloneBE.Infraction.Migrations
{
    [DbContext(typeof(Databasese))]
    [Migration("20250605082903_datanew")]
    partial class datanew
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CloneBE.Domain.EF.AppIdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "125e9ac4-c829-4c85-963f-573d091ef5f7",
                            ConcurrencyStamp = "0bde8134-a9c5-45ca-828a-8cb31efb4470",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("CloneBE.Domain.EF.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "39f18a9b-ebfa-44ff-b5ee-b54febe86ae2",
                            AccessFailedCount = 0,
                            Address = " g",
                            CartId = 0,
                            ConcurrencyStamp = "60023917-7d7a-4655-b75b-08f223f53f01",
                            Email = "honganh@gmail.com",
                            EmailConfirmed = true,
                            FullName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "HONGANH@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEDU9mYq4FmjSZILaz8GCxnTVgPiPOdRYrt1pcfnkYQDLfAYW5WPn1ZQD+qN4c2//uQ==",
                            PhoneNumber = "0123456789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "14e57540-30a9-4c53-bd8b-ea1108137898",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("CloneBE.Domain.EF.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"), 1L, 1);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CartId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("carts");
                });

            modelBuilder.Entity("CloneBE.Domain.EF.CartItem", b =>
                {
                    b.Property<int>("CartitemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartitemId"), 1L, 1);

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("Productid")
                        .HasColumnType("int");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<int>("quanlity")
                        .HasColumnType("int");

                    b.HasKey("CartitemId");

                    b.HasIndex("CartId");

                    b.HasIndex("Productid");

                    b.ToTable("cartItems");
                });

            modelBuilder.Entity("CloneBE.Domain.EF.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Lightweight and portable laptops",
                            Name = "Ultrabooks"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "High performance laptops for gaming",
                            Name = "Gaming Laptops"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Laptops designed for business use",
                            Name = "Business Laptops"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Convertible laptops with touchscreen",
                            Name = "2-in-1 Laptops"
                        },
                        new
                        {
                            CategoryId = 5,
                            Description = "Affordable laptops for everyday use",
                            Name = "Budget Laptops"
                        },
                        new
                        {
                            CategoryId = 6,
                            Description = "Powerful laptops for professional work",
                            Name = "Workstations"
                        });
                });

            modelBuilder.Entity("CloneBE.Domain.EF.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("CloneBE.Domain.EF.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"), 1L, 1);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.ToTable("orderDetails");
                });

            modelBuilder.Entity("CloneBE.Domain.EF.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<int?>("CategoryId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkImagesPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Price")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<int?>("stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "High quality Ultrabook with excellent features, model 1.",
                            LinkImagesPath = "images/ultrabook_model_1.jpg",
                            Name = "Ultrabook Model 1",
                            Price = 1983.6300000000001,
                            stock = 12
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "High quality Ultrabook with excellent features, model 2.",
                            LinkImagesPath = "images/ultrabook_model_2.jpg",
                            Name = "Ultrabook Model 2",
                            Price = 2611.0599999999999,
                            stock = 8
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Description = "High quality Ultrabook with excellent features, model 3.",
                            LinkImagesPath = "images/ultrabook_model_3.jpg",
                            Name = "Ultrabook Model 3",
                            Price = 2747.5599999999999,
                            stock = 67
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            Description = "High quality Ultrabook with excellent features, model 4.",
                            LinkImagesPath = "images/ultrabook_model_4.jpg",
                            Name = "Ultrabook Model 4",
                            Price = 1634.98,
                            stock = 93
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1,
                            Description = "High quality Ultrabook with excellent features, model 5.",
                            LinkImagesPath = "images/ultrabook_model_5.jpg",
                            Name = "Ultrabook Model 5",
                            Price = 2414.77,
                            stock = 68
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 1,
                            Description = "High quality Ultrabook with excellent features, model 6.",
                            LinkImagesPath = "images/ultrabook_model_6.jpg",
                            Name = "Ultrabook Model 6",
                            Price = 2845.9099999999999,
                            stock = 49
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1,
                            Description = "High quality Ultrabook with excellent features, model 7.",
                            LinkImagesPath = "images/ultrabook_model_7.jpg",
                            Name = "Ultrabook Model 7",
                            Price = 1497.6199999999999,
                            stock = 17
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 1,
                            Description = "High quality Ultrabook with excellent features, model 8.",
                            LinkImagesPath = "images/ultrabook_model_8.jpg",
                            Name = "Ultrabook Model 8",
                            Price = 1736.77,
                            stock = 86
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 1,
                            Description = "High quality Ultrabook with excellent features, model 9.",
                            LinkImagesPath = "images/ultrabook_model_9.jpg",
                            Name = "Ultrabook Model 9",
                            Price = 574.34000000000003,
                            stock = 78
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 1,
                            Description = "High quality Ultrabook with excellent features, model 10.",
                            LinkImagesPath = "images/ultrabook_model_10.jpg",
                            Name = "Ultrabook Model 10",
                            Price = 510.61000000000001,
                            stock = 39
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 2,
                            Description = "High quality Gaming Laptop with excellent features, model 1.",
                            LinkImagesPath = "images/gaming_laptop_model_1.jpg",
                            Name = "Gaming Laptop Model 1",
                            Price = 1295.2,
                            stock = 71
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 2,
                            Description = "High quality Gaming Laptop with excellent features, model 2.",
                            LinkImagesPath = "images/gaming_laptop_model_2.jpg",
                            Name = "Gaming Laptop Model 2",
                            Price = 624.09000000000003,
                            stock = 41
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 2,
                            Description = "High quality Gaming Laptop with excellent features, model 3.",
                            LinkImagesPath = "images/gaming_laptop_model_3.jpg",
                            Name = "Gaming Laptop Model 3",
                            Price = 1842.6199999999999,
                            stock = 80
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 2,
                            Description = "High quality Gaming Laptop with excellent features, model 4.",
                            LinkImagesPath = "images/gaming_laptop_model_4.jpg",
                            Name = "Gaming Laptop Model 4",
                            Price = 1710.27,
                            stock = 8
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 2,
                            Description = "High quality Gaming Laptop with excellent features, model 5.",
                            LinkImagesPath = "images/gaming_laptop_model_5.jpg",
                            Name = "Gaming Laptop Model 5",
                            Price = 1318.6600000000001,
                            stock = 33
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 2,
                            Description = "High quality Gaming Laptop with excellent features, model 6.",
                            LinkImagesPath = "images/gaming_laptop_model_6.jpg",
                            Name = "Gaming Laptop Model 6",
                            Price = 1568.75,
                            stock = 74
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 2,
                            Description = "High quality Gaming Laptop with excellent features, model 7.",
                            LinkImagesPath = "images/gaming_laptop_model_7.jpg",
                            Name = "Gaming Laptop Model 7",
                            Price = 988.94000000000005,
                            stock = 46
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 2,
                            Description = "High quality Gaming Laptop with excellent features, model 8.",
                            LinkImagesPath = "images/gaming_laptop_model_8.jpg",
                            Name = "Gaming Laptop Model 8",
                            Price = 1274.4300000000001,
                            stock = 62
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 2,
                            Description = "High quality Gaming Laptop with excellent features, model 9.",
                            LinkImagesPath = "images/gaming_laptop_model_9.jpg",
                            Name = "Gaming Laptop Model 9",
                            Price = 1579.5999999999999,
                            stock = 25
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 2,
                            Description = "High quality Gaming Laptop with excellent features, model 10.",
                            LinkImagesPath = "images/gaming_laptop_model_10.jpg",
                            Name = "Gaming Laptop Model 10",
                            Price = 926.39999999999998,
                            stock = 89
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 3,
                            Description = "High quality Business Laptop with excellent features, model 1.",
                            LinkImagesPath = "images/business_laptop_model_1.jpg",
                            Name = "Business Laptop Model 1",
                            Price = 575.89999999999998,
                            stock = 41
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 3,
                            Description = "High quality Business Laptop with excellent features, model 2.",
                            LinkImagesPath = "images/business_laptop_model_2.jpg",
                            Name = "Business Laptop Model 2",
                            Price = 1667.8299999999999,
                            stock = 20
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = 3,
                            Description = "High quality Business Laptop with excellent features, model 3.",
                            LinkImagesPath = "images/business_laptop_model_3.jpg",
                            Name = "Business Laptop Model 3",
                            Price = 1272.54,
                            stock = 88
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryId = 3,
                            Description = "High quality Business Laptop with excellent features, model 4.",
                            LinkImagesPath = "images/business_laptop_model_4.jpg",
                            Name = "Business Laptop Model 4",
                            Price = 2006.95,
                            stock = 29
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 3,
                            Description = "High quality Business Laptop with excellent features, model 5.",
                            LinkImagesPath = "images/business_laptop_model_5.jpg",
                            Name = "Business Laptop Model 5",
                            Price = 2869.5500000000002,
                            stock = 32
                        },
                        new
                        {
                            ProductId = 26,
                            CategoryId = 3,
                            Description = "High quality Business Laptop with excellent features, model 6.",
                            LinkImagesPath = "images/business_laptop_model_6.jpg",
                            Name = "Business Laptop Model 6",
                            Price = 1269.6800000000001,
                            stock = 75
                        },
                        new
                        {
                            ProductId = 27,
                            CategoryId = 3,
                            Description = "High quality Business Laptop with excellent features, model 7.",
                            LinkImagesPath = "images/business_laptop_model_7.jpg",
                            Name = "Business Laptop Model 7",
                            Price = 1909.8199999999999,
                            stock = 34
                        },
                        new
                        {
                            ProductId = 28,
                            CategoryId = 3,
                            Description = "High quality Business Laptop with excellent features, model 8.",
                            LinkImagesPath = "images/business_laptop_model_8.jpg",
                            Name = "Business Laptop Model 8",
                            Price = 2945.2800000000002,
                            stock = 97
                        },
                        new
                        {
                            ProductId = 29,
                            CategoryId = 3,
                            Description = "High quality Business Laptop with excellent features, model 9.",
                            LinkImagesPath = "images/business_laptop_model_9.jpg",
                            Name = "Business Laptop Model 9",
                            Price = 2730.5700000000002,
                            stock = 46
                        },
                        new
                        {
                            ProductId = 30,
                            CategoryId = 3,
                            Description = "High quality Business Laptop with excellent features, model 10.",
                            LinkImagesPath = "images/business_laptop_model_10.jpg",
                            Name = "Business Laptop Model 10",
                            Price = 1130.72,
                            stock = 92
                        },
                        new
                        {
                            ProductId = 31,
                            CategoryId = 4,
                            Description = "High quality 2-in-1 Laptop with excellent features, model 1.",
                            LinkImagesPath = "images/2in1_laptop_model_1.jpg",
                            Name = "2-in-1 Laptop Model 1",
                            Price = 852.25,
                            stock = 90
                        },
                        new
                        {
                            ProductId = 32,
                            CategoryId = 4,
                            Description = "High quality 2-in-1 Laptop with excellent features, model 2.",
                            LinkImagesPath = "images/2in1_laptop_model_2.jpg",
                            Name = "2-in-1 Laptop Model 2",
                            Price = 1602.3099999999999,
                            stock = 29
                        },
                        new
                        {
                            ProductId = 33,
                            CategoryId = 4,
                            Description = "High quality 2-in-1 Laptop with excellent features, model 3.",
                            LinkImagesPath = "images/2in1_laptop_model_3.jpg",
                            Name = "2-in-1 Laptop Model 3",
                            Price = 727.42999999999995,
                            stock = 31
                        },
                        new
                        {
                            ProductId = 34,
                            CategoryId = 4,
                            Description = "High quality 2-in-1 Laptop with excellent features, model 4.",
                            LinkImagesPath = "images/2in1_laptop_model_4.jpg",
                            Name = "2-in-1 Laptop Model 4",
                            Price = 2049.5500000000002,
                            stock = 48
                        },
                        new
                        {
                            ProductId = 35,
                            CategoryId = 4,
                            Description = "High quality 2-in-1 Laptop with excellent features, model 5.",
                            LinkImagesPath = "images/2in1_laptop_model_5.jpg",
                            Name = "2-in-1 Laptop Model 5",
                            Price = 649.75,
                            stock = 86
                        },
                        new
                        {
                            ProductId = 36,
                            CategoryId = 4,
                            Description = "High quality 2-in-1 Laptop with excellent features, model 6.",
                            LinkImagesPath = "images/2in1_laptop_model_6.jpg",
                            Name = "2-in-1 Laptop Model 6",
                            Price = 722.19000000000005,
                            stock = 40
                        },
                        new
                        {
                            ProductId = 37,
                            CategoryId = 4,
                            Description = "High quality 2-in-1 Laptop with excellent features, model 7.",
                            LinkImagesPath = "images/2in1_laptop_model_7.jpg",
                            Name = "2-in-1 Laptop Model 7",
                            Price = 583.40999999999997,
                            stock = 96
                        },
                        new
                        {
                            ProductId = 38,
                            CategoryId = 4,
                            Description = "High quality 2-in-1 Laptop with excellent features, model 8.",
                            LinkImagesPath = "images/2in1_laptop_model_8.jpg",
                            Name = "2-in-1 Laptop Model 8",
                            Price = 1451.1700000000001,
                            stock = 87
                        },
                        new
                        {
                            ProductId = 39,
                            CategoryId = 4,
                            Description = "High quality 2-in-1 Laptop with excellent features, model 9.",
                            LinkImagesPath = "images/2in1_laptop_model_9.jpg",
                            Name = "2-in-1 Laptop Model 9",
                            Price = 1356.5699999999999,
                            stock = 25
                        },
                        new
                        {
                            ProductId = 40,
                            CategoryId = 4,
                            Description = "High quality 2-in-1 Laptop with excellent features, model 10.",
                            LinkImagesPath = "images/2in1_laptop_model_10.jpg",
                            Name = "2-in-1 Laptop Model 10",
                            Price = 2028.5799999999999,
                            stock = 12
                        },
                        new
                        {
                            ProductId = 41,
                            CategoryId = 5,
                            Description = "High quality Budget Laptop with excellent features, model 1.",
                            LinkImagesPath = "images/budget_laptop_model_1.jpg",
                            Name = "Budget Laptop Model 1",
                            Price = 2016.03,
                            stock = 48
                        },
                        new
                        {
                            ProductId = 42,
                            CategoryId = 5,
                            Description = "High quality Budget Laptop with excellent features, model 2.",
                            LinkImagesPath = "images/budget_laptop_model_2.jpg",
                            Name = "Budget Laptop Model 2",
                            Price = 538.02999999999997,
                            stock = 52
                        },
                        new
                        {
                            ProductId = 43,
                            CategoryId = 5,
                            Description = "High quality Budget Laptop with excellent features, model 3.",
                            LinkImagesPath = "images/budget_laptop_model_3.jpg",
                            Name = "Budget Laptop Model 3",
                            Price = 1384.6900000000001,
                            stock = 59
                        },
                        new
                        {
                            ProductId = 44,
                            CategoryId = 5,
                            Description = "High quality Budget Laptop with excellent features, model 4.",
                            LinkImagesPath = "images/budget_laptop_model_4.jpg",
                            Name = "Budget Laptop Model 4",
                            Price = 2717.1199999999999,
                            stock = 85
                        },
                        new
                        {
                            ProductId = 45,
                            CategoryId = 5,
                            Description = "High quality Budget Laptop with excellent features, model 5.",
                            LinkImagesPath = "images/budget_laptop_model_5.jpg",
                            Name = "Budget Laptop Model 5",
                            Price = 2545.6900000000001,
                            stock = 98
                        },
                        new
                        {
                            ProductId = 46,
                            CategoryId = 5,
                            Description = "High quality Budget Laptop with excellent features, model 6.",
                            LinkImagesPath = "images/budget_laptop_model_6.jpg",
                            Name = "Budget Laptop Model 6",
                            Price = 2220.4400000000001,
                            stock = 42
                        },
                        new
                        {
                            ProductId = 47,
                            CategoryId = 5,
                            Description = "High quality Budget Laptop with excellent features, model 7.",
                            LinkImagesPath = "images/budget_laptop_model_7.jpg",
                            Name = "Budget Laptop Model 7",
                            Price = 2810.1500000000001,
                            stock = 48
                        },
                        new
                        {
                            ProductId = 48,
                            CategoryId = 5,
                            Description = "High quality Budget Laptop with excellent features, model 8.",
                            LinkImagesPath = "images/budget_laptop_model_8.jpg",
                            Name = "Budget Laptop Model 8",
                            Price = 2488.79,
                            stock = 63
                        },
                        new
                        {
                            ProductId = 49,
                            CategoryId = 5,
                            Description = "High quality Budget Laptop with excellent features, model 9.",
                            LinkImagesPath = "images/budget_laptop_model_9.jpg",
                            Name = "Budget Laptop Model 9",
                            Price = 2006.98,
                            stock = 89
                        },
                        new
                        {
                            ProductId = 50,
                            CategoryId = 5,
                            Description = "High quality Budget Laptop with excellent features, model 10.",
                            LinkImagesPath = "images/budget_laptop_model_10.jpg",
                            Name = "Budget Laptop Model 10",
                            Price = 845.15999999999997,
                            stock = 60
                        },
                        new
                        {
                            ProductId = 51,
                            CategoryId = 6,
                            Description = "High quality Workstation with excellent features, model 1.",
                            LinkImagesPath = "images/workstation_model_1.jpg",
                            Name = "Workstation Model 1",
                            Price = 2996.8400000000001,
                            stock = 32
                        },
                        new
                        {
                            ProductId = 52,
                            CategoryId = 6,
                            Description = "High quality Workstation with excellent features, model 2.",
                            LinkImagesPath = "images/workstation_model_2.jpg",
                            Name = "Workstation Model 2",
                            Price = 2994.5,
                            stock = 89
                        },
                        new
                        {
                            ProductId = 53,
                            CategoryId = 6,
                            Description = "High quality Workstation with excellent features, model 3.",
                            LinkImagesPath = "images/workstation_model_3.jpg",
                            Name = "Workstation Model 3",
                            Price = 1060.25,
                            stock = 37
                        },
                        new
                        {
                            ProductId = 54,
                            CategoryId = 6,
                            Description = "High quality Workstation with excellent features, model 4.",
                            LinkImagesPath = "images/workstation_model_4.jpg",
                            Name = "Workstation Model 4",
                            Price = 873.73000000000002,
                            stock = 87
                        },
                        new
                        {
                            ProductId = 55,
                            CategoryId = 6,
                            Description = "High quality Workstation with excellent features, model 5.",
                            LinkImagesPath = "images/workstation_model_5.jpg",
                            Name = "Workstation Model 5",
                            Price = 627.95000000000005,
                            stock = 13
                        },
                        new
                        {
                            ProductId = 56,
                            CategoryId = 6,
                            Description = "High quality Workstation with excellent features, model 6.",
                            LinkImagesPath = "images/workstation_model_6.jpg",
                            Name = "Workstation Model 6",
                            Price = 1242.46,
                            stock = 68
                        },
                        new
                        {
                            ProductId = 57,
                            CategoryId = 6,
                            Description = "High quality Workstation with excellent features, model 7.",
                            LinkImagesPath = "images/workstation_model_7.jpg",
                            Name = "Workstation Model 7",
                            Price = 2767.7600000000002,
                            stock = 78
                        },
                        new
                        {
                            ProductId = 58,
                            CategoryId = 6,
                            Description = "High quality Workstation with excellent features, model 8.",
                            LinkImagesPath = "images/workstation_model_8.jpg",
                            Name = "Workstation Model 8",
                            Price = 1671.53,
                            stock = 77
                        },
                        new
                        {
                            ProductId = 59,
                            CategoryId = 6,
                            Description = "High quality Workstation with excellent features, model 9.",
                            LinkImagesPath = "images/workstation_model_9.jpg",
                            Name = "Workstation Model 9",
                            Price = 1171.49,
                            stock = 64
                        },
                        new
                        {
                            ProductId = 60,
                            CategoryId = 6,
                            Description = "High quality Workstation with excellent features, model 10.",
                            LinkImagesPath = "images/workstation_model_10.jpg",
                            Name = "Workstation Model 10",
                            Price = 1760.3499999999999,
                            stock = 87
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "39f18a9b-ebfa-44ff-b5ee-b54febe86ae2",
                            RoleId = "125e9ac4-c829-4c85-963f-573d091ef5f7"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CloneBE.Domain.EF.Cart", b =>
                {
                    b.HasOne("CloneBE.Domain.EF.AppUser", "User")
                        .WithOne("Cart")
                        .HasForeignKey("CloneBE.Domain.EF.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CloneBE.Domain.EF.CartItem", b =>
                {
                    b.HasOne("CloneBE.Domain.EF.Cart", "Cart")
                        .WithMany("cartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloneBE.Domain.EF.Product", "Product")
                        .WithMany("cartItems")
                        .HasForeignKey("Productid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CloneBE.Domain.EF.Order", b =>
                {
                    b.HasOne("CloneBE.Domain.EF.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("CloneBE.Domain.EF.OrderDetail", b =>
                {
                    b.HasOne("CloneBE.Domain.EF.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CloneBE.Domain.EF.Product", b =>
                {
                    b.HasOne("CloneBE.Domain.EF.Category", "category")
                        .WithMany("products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("CloneBE.Domain.EF.AppIdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CloneBE.Domain.EF.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CloneBE.Domain.EF.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("CloneBE.Domain.EF.AppIdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloneBE.Domain.EF.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CloneBE.Domain.EF.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CloneBE.Domain.EF.AppUser", b =>
                {
                    b.Navigation("Cart")
                        .IsRequired();
                });

            modelBuilder.Entity("CloneBE.Domain.EF.Cart", b =>
                {
                    b.Navigation("cartItems");
                });

            modelBuilder.Entity("CloneBE.Domain.EF.Category", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("CloneBE.Domain.EF.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("CloneBE.Domain.EF.Product", b =>
                {
                    b.Navigation("cartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
